version: '3.4'
services:
  notebook:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/LVIV-2021
      #- ../neuralpredictors/:/src/neuralpredictors
      - ./notebooks:/content
      - ${DATA_PATH:-./data}:/content/data
    ports:
      - "7777:8888"
    env_file:
      - .env
