version: '3.4'
services:
  notebook:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src/LVIV-2021
      - ./notebooks:/content
      - ${DATA_PATH:-./data}:/content/data
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
