version: '3.4'
x-build: &build
  context: .
  dockerfile: Dockerfile
  
x-shared: &common
  image: at-docker:5000/nnexplore
  ipc: host
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DEV_SOURCE=${DEV_SOURCE}
  volumes:
    - .:/src/Iviv-2021
    - ../vivid:/src/vivid
    - ./notebooks:/notebooks/nnexplore
    - ${DATA_PATH:-./data}:/data
    - ${NOTEBOOK_PATH:-~/notebooks}:/notebooks/local
  env_file:
    - .env

services:
  notebook:
    <<: *common
    ports:
      - "${JUPYTER_HOST:-0.0.0.0}:${JUPYTER_PORT:-8888}:8888"
      - "${JUPYTER_HOST:-0.0.0.0}:${ST_PORT:-8501}:8501"
